### ISSUE TITLE
Will there be more community calls in the future

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/community#1]
I tried joining today w/previous link but meeting never started; here it says last meeting was Oct. 6.

**Comment by ccordoba12** [comment]
Yes, there will be. I just updated our Readme with the new date. We decided to make the call next Wednesday instead of this one (sorry for not communicating that on time).

**Comment by eafpres** [comment]
Well, I missed it as I didn't get it onto my calendar!  I've now followed this repo so hopefully I get notification when you update the next one, LoL

**Comment by ccordoba12** [comment]
Ok, sorry about that.
